apiVersion: v1
kind: Service
metadata:
    labels:
        app: microservice-java
    name: microservice-java
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: microservice-java
  type: LoadBalancer