apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-nodejs-deployment
spec:
  selector:
    matchLabels:
      app: microservice-nodejs
  replicas: 2
  template:
    metadata:
      labels:
        app: microservice-nodejs
    spec:
      containers:
      - name: microservice-nodejs
        image: 066203203749.dkr.ecr.eu-west-2.amazonaws.com/microservice-nodejs:1.0.0-SNAPSHOT.jar
        ports:
        - containerPort: 8080