apiVersion: v1
kind: Service
metadata:
    labels:
        app: microservice-nodejs-service
    name: microservice-nodejs-service
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: microservice-nodejs
  type: LoadBalancer