---
- hosts: local
  tasks:
  - name: "Create Kubernetes Deployment for {{ MICROSERVICE_NAME }}"
    shell: "kubectl apply -f {{ MICROSERVICE_NAME }}-deployment.yml"

  - name: "Create Kubernetes Service for {{ MICROSERVICE_NAME }}"
    shell: "kubectl apply -f {{ MICROSERVICE_NAME }}-service.yml"
