---
- hosts: local
  tasks:
  - name: "Delete Kubernetes Service for {{ MICROSERVICE_NAME }}"
    shell: "export KUBECONFIG=$KUBECONFIG:$HOME/.kube/aws-eks-kubeconfig && kubectl delete service {{ MICROSERVICE_NAME }}-service"

  - name: "Delete Kubernetes Deployment for {{ MICROSERVICE_NAME }}"
    shell: "export KUBECONFIG=$KUBECONFIG:$HOME/.kube/aws-eks-kubeconfig && kubectl delete deployment {{ MICROSERVICE_NAME }}-deployment"